easy_words = ['aahs', 'aals', 'abas',
    'abba', 'abbe', 'abed', 
    'abet', 'able', 'ably', 
    'abos', 'abri', 'abut', 
    'abye', 'abys', 'aced', 
    'aces', 'ache', 'achy', 
    'acid', 'acme', 'acne', 
    'acre', 'acta', 'acts', 
    'acyl', 'adds', 'adit', 
    'ados', 'adze', 'aeon', 
    'aero', 'aery', 'afar', 
    'agar', 'agas', 'aged', 
    'agee', 'ager', 'ages', 
    'agha', 'agin', 'agio',
    'anga', 'anil', 'anis', 
    'ankh', 'anna', 'anoa', 
    'anon', 'ansa', 'anta', 
    'ante', 'anti', 'ants', 
    'anus', 'aped', 'bans', 
    'baps', 'barb', 'bard', 
    'bare', 'barf', 'bark', 
    'barm', 'barn', 'bars', 
    'base', 'bash', 'bask', 
    'bass', 'boob', 'coys', 
    'cozy', 'cock', 'cran',
    'crab', 'crag', 'cram', 
    'crap', 'craw', 'cred', 
    'crew', 'crib', 'cris', 
    'crit', 'croc', 'crop',
    'dice', 'dick', 'dido',
    'didy', 'died', 'diel',
    'dies', 'diet', 'diff',
    'difs', 'digs', 'dike',
    'dill', 'dime', 'dyke',
    'eddy', 'eggy', 'effs',
    'edge', 'edgy', 'edhs', 
    'edit', 'eels', 'eely', 
    'eery', 'effs', 'efts', 
    'egad', 'egal', 'eger', 
    'eggs', 'eggy', 'fame', 
    'fane', 'fang', 'fano', 
    'fans', 'fard', 'fare', 
    'farl', 'farm', 'faro', 
    'fart', 'fash', 'fast', 
    'fate', 'gird', 'girl', 
    'girn', 'giro', 'girt', 
    'gist', 'gite', 'gits', 
    'give', 'glad', 'glam', 
    'gled', 'glee', 'gleg',
    'huts', 'hwan', 'hyla', 
    'hymn', 'hype', 'hypo', 
    'hyps', 'hyte', 'iamb', 
    'ibex', 'ibis', 'iced', 
    'ices', 'ichs', 'jaws', 
    'jays', 'jazz', 'jean', 
    'jeed', 'jeep', 'jeer', 
    'jees', 'jeez', 'jefe', 
    'jehu', 'jell', 'jeon', 
    'jerk', 'jizz', 'kame', 
    'kami', 'kana', 'kane', 
    'kaon', 'kapa', 'kaph', 
    'karn', 'kart', 'kata', 
    'kats', 'kava', 'kayo', 
    'kays', 'lone', 'long', 
    'loof', 'look', 'loom', 
    'loon', 'loop', 'loos', 
    'loot', 'lope', 'lops', 
    'lord', 'lore', 'lorn',
    'made', 'mads', 'maes', 
    'mage', 'magi', 'mags', 
    'maid', 'mail', 'maim', 
    'main', 'mair', 'make', 
    'mako', 'male', 'maun', 
    'maut', 'mawn', 'maws', 
    'maxi', 'maya', 'mayo', 
    'mays', 'maze', 'mazy', 
    'mead', 'meal', 'mean', 
    'meat', 'mutt', 'mycs', 
    'myna', 'myth', 'naan', 
    'nabe', 'nabs', 'nada', 
    'naff', 'nags', 'naif', 
    'nail', 'nala', 'name',
    'nazi', 'neap', 'near', 
    'neat', 'nebs', 'neck', 
    'need', 'neem', 'neep', 
    'negs', 'neif', 'nema', 
    'nene', 'neon', 'ogle', 
    'ogre', 'ohed', 'ohia', 
    'ohms', 'oils', 'oily', 
    'oink', 'okas', 'okay', 
    'okeh', 'okes', 'okra', 
    'olds', 'poon', 'poop', 
    'poor', 'poos', 'pope', 
    'pops', 'pore', 'pork', 
    'porn', 'port', 'pose', 
    'posh', 'post', 'posy',
    'puri', 'purl', 'purr', 
    'purs', 'push', 'puss', 
    'puts', 'putt', 'putz', 
    'pyas', 'pyes', 'pyic', 
    'pyin', 'pyre', 'pyro', 
    'qadi', 'qaid', 'qats', 
    'qoph', 'quad', 'quag', 
    'quai', 'quay', 'quey', 
    'quid', 'quin', 'quip', 
    'quit', 'quiz', 'quod', 
    'race', 'rack', 'racy', 
    'rads', 'raff', 'raft', 
    'raga', 'rage', 'ragg', 
    'ragi', 'rags', 'raia',
    'reil', 'rely', 'reid',
    'rile', 'rill', 'rime', 
    'rims', 'rimy', 'rind', 
    'ring', 'rink', 'rins', 
    'riot', 'ripe', 'rips', 
    'rise', 'risk', 'rite',
    'sene', 'sent', 'sept', 
    'sera', 'sere', 'serf', 
    'sers', 'seta', 'sets', 
    'sett', 'sewn', 'sews', 
    'sext', 'sexy', 'shad', 
    'shag', 'shah', 'sham', 
    'shat', 'shaw', 'shay', 
    'shea', 'shed', 'shes', 
    'shew', 'shim', 'shin',
    'ship', 'shit', 'shiv', 
    'shmo', 'shod', 'shoe', 
    'shog', 'shoo', 'shop', 
    'shot', 'show', 'shri', 
    'shul', 'shun', 'shut',
    'sild', 'silk', 'sill', 
    'silo', 'silt', 'sima', 
    'simp', 'sims', 'sine', 
    'sing', 'sinh', 'sink', 
    'sins', 'sipe', 'tick', 
    'tics', 'tide', 'tidy', 
    'tied', 'tier', 'ties', 
    'tiff', 'tike', 'tiki', 
    'tile', 'till', 'tils', 
    'tilt', 'tits', 'tiny',
    'unau', 'unbe', 'unci', 
    'unco', 'unde', 'undo', 
    'undy', 'unit', 'unto', 
    'upas', 'upby', 'updo', 
    'upon', 'urbs', 'vacs', 
    'vagi', 'vail', 'vain', 
    'vair', 'vale', 'vamp', 
    'vane', 'vang', 'vans', 
    'vara', 'vars', 'vary', 
    'vasa', 'vice', 'vide', 
    'vids', 'vied', 'vier', 
    'vies', 'view', 'viga', 
    'vigs', 'vile', 'vill', 
    'vims', 'vina', 'vine',
    'wage', 'wags', 'waif', 
    'wail', 'wain', 'wair', 
    'wait', 'wake', 'wale', 
    'walk', 'wall', 'waly', 
    'wame', 'wand', 'wife',
    'yegg', 'yeld', 'yelk', 
    'yell', 'yelp', 'yens', 
    'yeps', 'yerk', 'yeti', 
    'yett', 'yeuk', 'yews', 
    'yids', 'yill', 'yogi',
    'zips', 'ziti', 'zits', 
    'zoea', 'zoic', 'zona', 
    'zone', 'zonk', 'zoom', 
    'zoon', 'zoos', 'zori', 
    'zouk', 'zyme']

normal_words = ["Adult", "Agent", "Apple", 
    "Bird", "Beach", "Blood",
    "Chain", "Cream", "Clock",
    "Drink", "Death", "Dance",
    "Enemy", "Error", "Event",
    "Fight", "Frame", "Fruit",
    "Glass", "Grass", "Guide",
    "Horse", "House", "Heart",
    "Image", "Index", "Issue",
    "Japan", "Judge", "Jones",
    "Layer", "Level", "Light",
    "Metal", "Money", "March",
    "Night", "North", "Nurse",
    "Order", "Other", "Offer",
    "Paper", "Party", "Plane",
    "Ratio", "Reply", "River",
    "Shape", "Scone", "Squad",
    "Taste", "Tower", "Train",
    "Union", "Uncle", "Unity",
    "Video", "Voice", "Visit",
    "Waste", "White", "World",
    "Youth", "Young", "Yeech"]

hard_words = ['Jimjams','AARRGHH', 'ABACTOR', 
'ABALONE', 'ABANDED', 'ABANDON', 'ABASERS', 
'ABASHED', 'ABASHES', 'ABASIAS', 'ABASING',
'ABJECTS', 'ABJOINT', 'ABJURED', 'ABJURER', 
'ABJURES', 'ABLATED', 'ABLATES', 'ABLATOR', 
'ABLAUTS', 'ABLEISM', 'ALDOSES', 'ALDRINS', 
'ALECOST', 'ALEGARS', 'ALEGGED', 'ALEGGES', 
'ALEMBIC', 'ALENCON', 'ALENGTH', 'ALEPINE',
'BACLAVA', 'BACONER', 'BACULUM', 'BADDEST', 
'BADDIES', 'BADDISH', 'BADGERS', 'BADGING', 
'BADIOUS', 'BADLAND', 'BEEPING', 'BEERAGE', 
'BEERIER', 'BEERILY', 'BEESOME', 'BEESWAX', 
'BEETFLY', 'BEETING', 'BEETLED', 'BEETLER',
'BENUMBS', 'BENZALS', 'BENZENE', 'BENZILS', 
'BENZINE', 'BENZINS', 'BENZOIC', 'BENZOIN',
'BENZOLE', 'BENZOLS', 'BERSERK', 'BERTHAS', 
'BERTHED', 'BERTHES', 'BESAINT', 'BESCOUR', 
'BESEECH', 'BESEEKE', 'BESEEMS', 'BESHAME',
'BOGONGS', 'BOGUSLY', 'BOGWOOD', 'BOGYISM', 
'BOGYMAN', 'BOGYMEN', 'BOHEMIA', 'BOHRIUM', 
'BOHUNKS', 'BOILERS' 'BUDDLES', 'BUDGERO', 
'BUDGERS', 'BUDGETS', 'BUDGIES', 'BUDGING', 
'BUDLESS', 'BUDLIKE', 'BUDMASH', 'BUDWORM',
'BUMKINS', 'BUMMALO', 'BUMMELS', 'BUMMERS', 
'BUMMEST', 'BUMMING', 'BUMMLED', 'BUMMLES', 
'BUMMOCK', 'BUMPERS', 'CAMMIES', 'CAMMING', 
'CAMOGIE', 'CAMOODI', 'CAMORRA', 'CAMOTES', 
'CAMPANA', 'CAMPERS', 'CAMPEST', 'CAMPHOL',
'CAPSULE', 'CAPTAIN', 'CAPTANS', 'CAPTION', 
'CAPTIVE', 'CAPTORS', 'CAPTURE', 'CAPUCHE', 
'CAPUERA', 'CARABAO', 'CHEEROS', 'CHEESED', 
'CHEESES', 'CHEETAH', 'CHEFDOM', 'CHEFFED', 
'CHEFING', 'CHEGOES', 'CHEKIST', 'CHELATE',
'CHILLIS', 'CHILLUM', 'CHIMARS', 'CHIMBLY', 
'CHIMERA', 'CHIMERE', 'CHIMERS', 'CHIMING', 
'CHIMLAS', 'CHIMLEY', 'COADMIT', 'COAEVAL', 
'COAGENT', 'COAGULA', 'COAITAS', 'COALBIN', 
'COALBOX', 'COALERS', 'COALIER', 'COALIFY',
'CURTEST', 'CURTESY', 'CURTSEY', 'CURVATE', 
'CURVETS', 'CURVIER', 'CURVING', 'CURVITY', 
'CUSHATS', 'CUSHAWS', 'CURVEY', 'DACRONS', 
'DACTYLI', 'DACTYLS', 'DADAISM', 'DADAIST', 
'DADDIES', 'DADDING', 'DADDLED', 'DADDLES', 
'DADDOCK', 'DENUDED', 'DENUDER', 'DENUDES', 
'DENYING', 'DEODAND', 'DEODARA', 'DEODARS', 
'DEODATE', 'DEONTIC', 'DEORBIT', 'DEXTERS', 
'DEXTRAL', 'DEXTRAN', 'DEXTRIN', 'DEZINCS', 
'DHAMMAS', 'DHANSAK', 'DHARMAS', 'DHARMIC', 
'DHARNAS', 'DONGOLA', 'DONINGS', 'DONJONS', 
'DONKEYS', 'DONNARD', 'DONNART', 'DONNATS', 
'DONNEES', 'DONNERD', 'DONNERT', 'DURGIER', 
'DURIANS', 'DURIONS', 'DURMAST', 'DURNING', 
'DURRIES', 'DUSHING', 'DUSKENS', 'DUSKEST', 
'DUSKIER', 'EFFORCE', 'EFFORTS', 'EFFRAYS', 
'EFFULGE', 'EFFUSED', 'EFFUSES', 'EFTSOON', 
'EGALITE', 'EGALITY', 'EGENCES', 'EPITAPH', 
'EPITAXY', 'EPITHEM', 'EPITHET', 'EPITOME', 
'EPITOPE', 'EPIZOAN', 'EPIZOIC', 'EPIZOON', 
'EPOCHAL', 'EPOCHAS', 'EPONYMS', 'FATUOUS', 
'FATWAED', 'FATWAHS', 'FATWOOD', 'FAUCALS', 
'FAUCETS', 'FAUCHON', 'FAUCIAL', 'FAULTED', 
'FAUNIST', 'FEEDLOT', 'FEELBAD', 'FEELERS', 
'FEELESS', 'FEELING', 'FEERIES', 'FEERING', 
'FEERINS', 'FEESING', 'FEEZING', 'FLUVIAL', 
'FLUXING', 'FLUXION', 'FLUXIVE', 'FLYABLE', 
'FLYAWAY', 'FLYBACK', 'FLYBANE', 'FLYBELT', 
'FLYBLEW', 'FOOTLED', 'FOOTLER', 'FOOTLES', 
'FOOTMAN', 'FOOTMEN', 'FOOTPAD', 'FOOTRAS', 
'FOOTROT', 'FOOTSIE', 'FOOTWAY', 'FUTZING', 
'FUZZIER', 'FUZZILY', 'FUZZING', 'FUZZLED', 
'FUZZLES', 'FYLFOTS', 'GABBARD', 'GABBART', 
'GABBERS', 'GALLOCK', 'GALLONS', 'GALLOON', 
'GALLOOT', 'GALLOPS', 'GALLOUS', 'GALLOWS', 
'GALOCHE', 'GALOOTS', 'GALOPED', 'GLYPTAL', 
'GLYPTIC', 'GNARLED', 'GNARRED', 'GNASHED', 
'GNASHER', 'GNASHES', 'GNATHAL', 'GNATHIC', 
'GNAWERS', 'GOBONEE', 'GOBURRA', 'GODDAMN', 
'GODDAMS', 'GODDENS', 'GODDESS', 'GODDING', 
'GODETIA', 'GODHEAD', 'GODHOOD', 'GUSLARS', 
'GUSSETS', 'GUSSIED', 'GUSSIES', 'GUSTFUL', 
'GUSTIER', 'GUSTILY', 'GUSTING', 'GUSTOES', 
'GUTCHER', 'GYNECIA', 'GYNECIC', 'GYNNEYS', 
'GYNNIES', 'GYPLURE', 'GYPPERS', 'GYPPIES', 
'GYPPING', 'GYPSIED', 'GYPSIES', 'HANGERS', 
'HANGING', 'HANGMAN', 'HANGMEN', 'HANGOUT', 
'HANGTAG', 'HANGUPS', 'HANJARS', 'HANKERS', 
'HANKIES', 'HEROINE', 'HEROINS', 'HEROISE', 
'HEROISM', 'HEROIZE', 'HERONRY', 'HEROONS', 
'HERRIED', 'HERRIES', 'HERRING', 'HEWINGS', 
'HEXACTS', 'HEXADES', 'HEXADIC', 'HEXAGON', 
'HEXANES', 'HEXAPLA', 'HEXAPOD', 'HEXARCH', 
'HEXENES', 'HYENOID', 'HYGEIST', 'HYGIENE', 
'HYGROMA', 'HYLDING', 'HYLISMS', 'HYLISTS', 
'HYLOIST', 'HYMENAL', 'HYMENIA', 'ICELESS',
'IMAGINE', 'IMAGING', 'IMAGISM', 'IMAGIST', 
'IMAGOES', 'IMAMATE', 'IMARETS', 'IMBALMS', 
'IMBARKS', 'IMBASED', 'ISOLATE', 'ISOLEAD', 
'ISOLINE', 'ISOLOGS', 'ISOMERE', 'ISOMERS', 
'ISONOME', 'ISONOMY', 'ISOPACH', 'ISOPODS',
'JAGGERS', 'JAGGERY', 'JAGGIER', 'JAGGIES', 
'JAGGING', 'JAGHIRE', 'JAGHIRS', 'JAGLESS', 
'JAGUARS', 'JAILERS', 'JONQUIL', 'JONTIES', 
'JOOKERY', 'JOOKING', 'JORDANS', 'JOSEPHS', 
'JOSHERS', 'JOSHING', 'JOSKINS', 'JOSSERS', 
'KASBAHS', 'KASHERS', 'KASHMIR', 'KASHRUS', 
'KASHRUT', 'KATANAS', 'KATCINA', 'KATHAKS', 
'KATHODE', 'KATIONS', 'KERRIAS', 'KERRIES', 
'KERSEYS', 'KERVING', 'KERYGMA', 'KESTING', 
'KESTREL', 'KETCHES', 'KETCHUP', 'KETENES', 
'KILLICK', 'KILLIES', 'KILLING', 'KILLJOY', 
'KILLOCK', 'KILLUTS', 'KILNING', 'KILOBAR', 
'KILOBIT', 'KILORAD', 'KOEKOEA', 'KOFTGAR', 
'KOKAKOS', 'KOKANEE', 'KOKOBEH', 'KOKOWAI', 
'KOLACKY', 'KOLBASI', 'KOLHOZY', 'KOLKHOS', 
'LABROID', 'LABROSE', 'LABRUMS', 'LACIEST', 
'LACINGS', 'LACINIA', 'LACKERS', 'LACKEYS', 
'LACKING', 'LACONIC', 'LANDERS', 'LANDING', 
'LANDLER', 'LANDMAN', 'LANDMEN', 'LANEWAY', 
'LANGAHA', 'LANGARS', 'LANGERS', 'LANGEST', 
'LASHINS', 'LASHKAR', 'LASINGS', 'LASKETS', 
'LASQUES', 'LASSIES', 'LASSOCK', 'LASSOED', 
'LASSOER', 'LASSOES', 'LOBULUS', 'LOBWORM', 
'LOCALES', 'LOCALLY', 'LOCATED', 'LOCATER', 
'LOCATES', 'LOCATOR', 'LOCHANS', 'LOCHIAL',
'LOOFFUL', 'LOOKERS', 'LOOKING', 'LOOKISM', 
'LOOKIST', 'LOOKOUT', 'LOOKUPS', 'LOOMING', 
'LOONEYS', 'LOONIER', 'LOONIES', 'LOONILY', 
'LOONING', 'MARIMBA', 'MARINAS', 'MARINER', 
'MARINES', 'MARITAL', 'MARKERS', 'MARKETS', 
'MARKHOR', 'MARKING', 'MARKKAA', 'MARKKAS', 
'MARKMAN', 'MARKMEN', 'METAZOA', 'METCAST', 
'METEORS', 'METEPAS', 'METERED', 'METHANE', 
'METHINK', 'METHODS', 'METHOXY', 'METHYLS',
'MINUSES', 'MINUTED', 'MINUTER', 'MINUTES', 
'MINUTIA', 'MINXISH', 'MINYANS', 'MIOCENE', 
'MIOMBOS', 'MIOTICS', 'MOOTERS', 'MOOTEST', 
'MOOTING', 'MOOTMAN', 'MOOTMEN', 'MOOVING', 
'MOPANES', 'MOPANIS', 'MOPHEAD', 'MOPIEST',
'MUKTUKS', 'MULATTA', 'MULATTO', 'MULCHED', 
'MULCHES', 'MULCTED', 'MULESED', 'MULESES', 
'MULETAS', 'MULLAHS', 'NOCTURN', 'NOCUOUS', 
'NODALLY', 'NODATED', 'NODDERS', 'NODDIER', 
'NODDIES', 'NODDING', 'NODDLED', 'NODDLES',
'NUNCIOS', 'NUNCLES', 'NUNDINE', 'NUNHOOD', 
'NUNLIKE', 'NUNNERY', 'NUNNISH', 'NUNSHIP', 
'NUPTIAL', 'NURAGHE', 'OAKMOSS', 'OARAGES', 
'OARFISH', 'OARIEST', 'OARLESS', 'OARLIKE', 
'OARLOCK', 'OARSMAN', 'OARSMEN', 'OARWEED',
'ORANGEY', 'ORARIAN', 'ORARION', 'ORARIUM', 
'ORATING', 'ORATION', 'ORATORS', 'ORATORY', 
'ORATRIX', 'ORBIEST', 'PALLING', 'PALLIUM', 
'PALLONE', 'PALLORS', 'PALMARY', 'PALMATE', 
'PALMERS', 'PALMFUL', 'PALMIER', 'PALMIES',
'PANTONS', 'PANTOUM', 'PANTUNS', 'PANZERS', 
'PAPABLE', 'PAPADAM', 'PAPADOM', 'PAPADUM', 
'PAPAINS', 'PAPALLY', 'PERTURB', 'PERTUSE', 
'PERUKED', 'PERUKES', 'PERUSAL', 'PERUSED', 
'PERUSER', 'PERUSES', 'PERVADE', 'PERVERT',
'PHOBIST', 'PHOCINE', 'PHOEBES', 'PHOEBUS', 
'PHOENIX', 'PHONATE', 'PHONEME', 'PHONERS', 
'PHONEYS', 'PHONICS', 'PLUCKED', 'PLUCKER', 
'PLUFFED', 'PLUGGED', 'PLUGGER', 'PLUGOLA', 
'PLUMAGE', 'PLUMATE', 'PLUMBED', 'PLUMBER',
'PRESSOR', 'PRESTED', 'PRESTER', 'PRESTOS', 
'PRESUME', 'PRETAPE', 'PRETEEN', 'PRETELL', 
'PRETEND', 'PRETERM', 'PULWARS', 'PUMELOS', 
'PUMICED', 'PUMICER', 'PUMICES', 'PUMMELO', 
'PUMMELS', 'PUMPERS', 'PUMPING', 'PUMPION',
'QUINARY', 'QUINATE', 'QUINCES', 'QUINCHE', 
'QUINELA', 'QUINIES', 'QUININA', 'QUININE', 
'QUININS', 'QUINNAT', 'RANTING', 'RANULAR', 
'RANULAS', 'RANZELS', 'RAOULIA', 'RAPHIAS', 
'RAPHIDE', 'RAPIDER', 'RAPIDLY', 'RAPIERS',
'RAPISTS', 'REEKIER', 'REEKING', 'REELECT', 
'REELERS', 'REELING', 'REELMAN', 'REELMEN', 
'REEMITS', 'REENACT', 'REENDOW', 'RHOMBIC', 
'RHOMBOI', 'RHOMBOS', 'RHOMBUS', 'RHONCHI',
'RHUBARB', 'RHUMBAS', 'RHYMERS', 'RHYMING',
'RHYMIST', 'ROOTLES', 'ROOTLET', 'ROPABLE', 
'ROPEWAY', 'ROPIEST', 'ROPINGS', 'ROQUETS', 
'RORIEST', 'RORQUAL', 'RORTERS', 'SABLING', 
'SABREUR', 'SABRING', 'SABURRA', 'SACATON', 
'SACBUTS', 'SACCADE', 'SACCATE', 'SACCULE', 
'SACCULI', 'SCENTED', 'SCEPSIS', 'SCEPTER', 
'SCEPTIC', 'SCEPTRE', 'SCEPTRY', 'SCERNED', 
'SCERNES', 'SCHANSE', 'SCHANZE', 'SCOURED', 
'SCOURER', 'SCOURGE', 'SCOURIE', 'SCOURSE', 
'SCOUSER', 'SCOUSES', 'SCOUTED', 'SCOUTER', 
'SCOUTHS', 'SCULPED', 'SCULPIN', 'SCULPTS', 
'SCULTCH', 'SCUMBAG', 'SCUMBER', 'SCUMBLE', 
'SCUMMED', 'SCUMMER', 'SCUNGED', 'SHEERER', 
'SHEERLY', 'SHEETED', 'SHEETER', 'SHEEVES', 
'SHEGETZ', 'SHEHITA', 'SHEIKHA', 'SHEIKHS', 
'SHEILAS', 'SHIPFUL', 'SHIPLAP', 'SHIPMAN', 
'SHIPMEN', 'SHIPPED', 'SHIPPEN', 'SHIPPER', 
'SHIPPIE', 'SHIPPON', 'SHIPPOS', 'SIRDARS', 
'SIRENIC', 'SIRGANG', 'SIRKARS', 'SIRLOIN', 
'SIRNAME', 'SIROCCO', 'SIROSET', 'SIRRAHS', 
'SIRREES', 'SLAYING', 'SLEAVED', 'SLEAVES', 
'SLEAZES', 'SLEDDED', 'SLEDDER', 'SLEDGED', 
'SLEDGER', 'SLEDGES', 'SLEECHY', 'SOWSING', 
'SOWSSED', 'SOWSSES', 'SOWTERS', 'SOWTHED', 
'SOYBEAN', 'SOYMILK', 'SOYUZES', 'SOZINES', 
'SOZZLED', 'SPARKLY', 'SPAROID', 'SPARRED', 
'SPARRER', 'SPARRES', 'SPARROW', 'SPARSER', 
'SPARTAN', 'SPARTHE', 'SPARTHS', 'SPOOKED', 
'SPOOLED', 'SPOOLER', 'SPOOMED', 'SPOONED', 
'SPOONEY', 'SPOORED', 'SPOORER', 'SPORING', 
'SPOROID', 'SQUEEZY', 'SQUELCH', 'SQUIDGE', 
'SQUIDGY', 'SQUIERS', 'SQUIFFY', 'SQUILLA', 
'SQUILLS', 'SQUINCH', 'SQUINNY', 'STAFFED', 
'STAFFER', 'STAGERS', 'STAGERY', 'STAGGED', 
'STAGGER', 'STAGGIE', 'STAGIER', 'STAGILY', 
'STAGING', 'STILTED', 'STILTER', 'STIMIED', 
'STIMIES', 'STIMING', 'STIMULI', 'STINGED', 
'STINGER', 'STINGOS', 'STINKER', 'STORGES', 
'STORIED', 'STORIES', 'STORING', 'STORMED', 
'STORMER', 'STOSSES', 'STOTINS', 'STOTTED', 
'STOTTER', 'SUNFISH', 'SUNGARS', 'SUNGLOW', 
'SUNHATS', 'SUNKETS', 'SUNKIES', 'SUNLAMP',
'SUNLAND', 'SUNLESS', 'SUNLIKE', 'SWEVENS', 
'SWEYING', 'SWIDDEN', 'SWIFTED', 'SWIFTER', 
'SWIFTIE', 'SWIFTLY', 'SWIGGED', 'SWIGGER', 
'SWILERS', 'SWOBBED', 'SWOBBER', 'SWOFFER', 
'SWOLLEN', 'SWOONED', 'SWOONER', 'SWOOPED', 
'SWOOPER', 'SWOPPED', 'SWOPPER', 'TECHIER', 
'TECHIES', 'TECHILY', 'TECHNIC', 'TECHNOS', 
'TECKELS', 'TECTITE', 'TECTRIX', 'TECTUMS', 
'TEDDERS', 'TELSONS', 'TEMBLOR', 'TEMENOS', 
'TEMPEHS', 'TEMPERA', 'TEMPERS', 'TEMPEST', 
'TEMPING', 'TEMPLAR', 'TEMPLED', 'TEREBRA', 
'TEREDOS', 'TEREFAH', 'TERETES', 'TERGITE', 
'TERMERS', 'TERMING', 'TERMINI', 'TERMITE', 
'TERMORS', 'TEXTING', 'TEXTUAL', 'TEXTURE', 
'THACKED', 'THAIRMS', 'THALAMI', 'THALERS', 
'THALIAN', 'THALLIC', 'THALLUS', 'TOCHERS', 
'TOCKIER', 'TOCKING', 'TOCKLEY', 'TOCSINS', 
'TODDIES', 'TODDING', 'TODDLED', 'TODDLER', 
'TODDLES', 'TOOLSET', 'TOOMEST', 'TOOMING', 
'TOONIES', 'TOORIES', 'TOOSHIE', 'TOOTERS', 
'TOOTHED', 'TOOTING', 'TOOTLED', 'TOPSMEN', 
'TOPSOIL', 'TOPSPIN', 'TOPWORK', 'TOQUETS', 
'TORANAS', 'TORCHED', 'TORCHER', 'TORCHES', 
'TORCHON', 'TRIMERS', 'TRIMMED', 'TRIMMER', 
'TRIMTAB', 'TRINARY', 'TRINDLE', 'TRINGLE', 
'TRINING', 'TRINITY', 'TRINKET', 'TRIDENT',
'TURNERY', 'TURNING', 'TURNIPS', 'TURNKEY', 
'TURNOFF', 'TURNONS', 'TURNOUT', 'TURNUPS', 
'TURPETH', 'TURRETS', 'TUSHIES', 'TUSHING', 
'TUSHKAR', 'TUSHKER', 'TUSKARS', 'TUSKERS', 
'TUSKIER', 'TUSKING', 'TUSSAHS', 'TUSSARS',
'UNHANDS', 'UNHANDY', 'UNHANGS', 'UNHAPPY', 
'UNHARDY', 'UNHASPS', 'UNHASTY', 'UNHEADS', 
'UNHEALS', 'UNHEARD', 'UNSAVED', 'UNSAWED', 
'UNSCALE', 'UNSCARY', 'UNSCREW', 'UNSEALS', 
'UNSEAMS', 'UNSEATS', 'UNSEELS', 'UNSEENS',
'UNSPELL', 'UNSPENT', 'UNSPIDE', 'UNSPIED', 
'UNSPILT', 'UNSPLIT', 'UNSPOKE', 'UNSPOOL', 
'UNSTACK', 'UNSTAID', 'UPTEMPO', 'UPTHREW', 
'UPTHROW', 'UPTICKS', 'UPTIGHT', 'UPTILTS', 
'UPTIMES', 'UPTOWNS', 'UPTRAIN', 'UPTREND',
'URIDINE', 'URINALS', 'URINANT', 'URINARY', 
'URINATE', 'URINING', 'URINOSE', 'URINOUS', 
'URNFULS', 'URNINGS', 'VAGALLY', 'VAGGING', 
'VAGINAE', 'VAGINAL', 'VAGINAS', 'VAGITUS', 
'VAGRANT', 'VAGUELY', 'VAGUEST', 'VAGUING',
'VENTRES', 'VENTURE', 'VENTURI', 'VENULAR', 
'VENULES', 'VENUSES', 'VERANDA', 'VERBALS', 
'VERBENA', 'VERBIDS', 'VESTIGE', 'VESTING', 
'VESTRAL', 'VESTURE', 'VETCHES', 'VETERAN', 
'VETIVER', 'VETKOEK', 'VETOERS', 'VETOING', 
'VINTING', 'VINTNER', 'VINYLIC', 'VIOLATE', 
'VIOLENT', 'VIOLERS', 'VIOLETS', 'VIOLINS', 
'VIOLIST', 'VIOLONE', 'VULNING', 'VULPINE', 
'VULTURE', 'VULTURN', 'VULVATE', 'VUMMING', 
'VUTTIER', 'VYINGLY', 'WABAINS', 'WABBLED',
'WANZING', 'WAPITIS', 'WAPPEND', 'WAPPERS', 
'WAPPING', 'WARAGIS', 'WARATAH', 'WARBIER', 
'WARBLED', 'WARBLER', 'WEEPIER', 'WEEPIES', 
'WEEPILY', 'WEEPING', 'WEETEST', 'WEETING', 
'WEEVERS', 'WEEVILS', 'WEEVILY', 'WEEWEED',
'WINGERS', 'WINGIER', 'WINGING', 'WINGLET', 
'WINGMAN', 'WINGMEN', 'WINGTIP', 'WINIEST', 
'WINKERS', 'WINKING', 'WORSING', 'WORSTED', 
'WORTHED', 'WORTLES', 'WOSBIRD', 'WOTCHER', 
'WOTTEST', 'WOTTETH', 'WOTTING', 'WOUBITS',
'XANTHIN', 'XENOPUS', 'XERAFIN', 'XERARCH', 
'XERASIA', 'XEROMAS', 'XEROSES', 'XEROSIS', 
'XEROTES', 'XEROTIC', 'YARDMEN', 'YARKING', 
'YARNERS', 'YARNING', 'YARPHAS', 'YARRANS', 
'YARROWS', 'YASHMAC', 'YASHMAK', 'YASMAKS',
'YOBBERY', 'YOBBISH', 'YOBBISM', 'YOBBOES', 
'YOCKING', 'YODELED', 'YODELER', 'YODLERS', 
'YODLING', 'YOGHURT', 'ZABETAS', 'ZABTIEH', 
'ZACATON', 'ZADDICK', 'ZADDIKS', 'ZAFFARS', 
'ZAFFERS', 'ZAFFIRS', 'ZAFFRES', 'ZAGGING',
'ZETETIC', 'ZEUGMAS', 'ZEUXITE', 'ZIBETHS', 
'ZIFFIUS', 'ZIGANKA', 'ZIGGING', 'ZIGZAGS', 
'ZIKURAT', 'ZILCHES', 'ZIPPIER', 'ZIPPING', 
'ZIRCONS', 'ZITHERN', 'ZITHERS', 'ZIZANIA', 
'ZIZZING', 'ZIZZLED', 'ZIZZLES', 'ZLOTIES',
'ZOOLOGY', 'ZOOMING', 'ZOONING', 'ZOONITE', 
'ZOONOMY', 'ZOOPERY', 'ZOOTAXY', 'ZOOTIER', 
'ZOOTOMY', 'ZOOTYPE', 'ZYMOGEN', 'ZYMOMES', 
'ZYMOSAN', 'ZYMOSES', 'ZYMOSIS', 'ZYMOTIC', 
'ZYMURGY', 'ZYTHUMS', 'ZYZZYVA']

combined_list = [easy_words, normal_words, hard_words]